### ISSUE TITLE
produce ressources after logout

### ISSUE THREAD

**Issue by ZengineAlex** [ZengineAlex/game#11]
how can be realized that ressources are produced even if the user is logged out?

**Comment by ZengineChris** [comment]
Same as #12

**Comment by ZengineAlex** [comment]
I have thought of the same, but imagine this situation; You log out and your resources will just be calculated when you log in again. What happens, if in the time you are not logged in someone attacks your village? Will he gather the amount of resources you had before you logged out? 

Hm...but while I'm writing this I think what you said can be taken over also for this situation:

You log out and a time stamp will register this. If now someone interacts with your village, the amount of resources can be calculated by comparing the time stamp from the logout with the time the interaction happens.

**Comment by ZengineAlex** [comment]
solved with #17
